require:
  - rubocop-performance

AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - 'Jarfile'
    - 'vendor/**/*'
    - 'Gemfile'
    - 'bin/**/*'

Style/Documentation:
  Enabled: false

# Disable for specs
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
