require:
  - rubocop-performance

AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable
  Exclude:
    - 'Jarfile'
    - 'vendor/**/*'
    - 'Gemfile'
    - 'bin/**/*'
    - 'spec/support/faux/**/*'

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  CountAsOne: ['array', 'hash', 'heredoc', 'method_call']

# Disable for specs
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
