require:
  - rubocop-performance

AllCops:
  NewCops: disable
  SuggestExtensions: false
  TargetRubyVersion: 2.5
  Exclude:
    - 'Jarfile'
    - 'vendor/**/*'
    - 'Gemfile'
    - 'bin/**/*'

#
# Specific settings for alignment indentation
#
Layout/CaseIndentation:
  Enabled: true
  EnforcedStyle: end

Layout/EndAlignment:
  Enabled: true
  EnforcedStyleAlignWith: variable

Layout/ParameterAlignment:
  Enabled: true
  SupportedStyles:
  - with_first_parameter
  - with_fixed_indentation

Layout/ArgumentAlignment:
  Enabled: true
  SupportedStyles:
  - with_first_parameter
  - with_fixed_indentation

Layout/HashAlignment:
  Enabled: true
  EnforcedHashRocketStyle: key
  EnforcedColonStyle: key
  EnforcedLastArgumentHashStyle: always_inspect
  SupportedLastArgumentHashStyles:
  - always_inspect
  - always_ignore
  - ignore_implicit
  - ignore_explicit

Layout/MultilineArrayBraceLayout:
  Enabled: true

Layout/MultilineBlockLayout:
  Enabled: true

Layout/MultilineMethodCallIndentation:
  Enabled: true
  EnforcedStyle: indented

Lint/UnusedMethodArgument:
  AllowUnusedKeywordArguments: true
  Exclude:
    - 'connectors/lib/connectors/fake_clients/google_drive.rb'

#
# Exceptions
#
Naming/MethodName:
  Exclude:
    - 'crawler/lib/crawler/http_client/all_trusting_trust_manager.rb'

Style/NumericLiterals:
  Exclude:
    - !ruby/regexp /_spec\.rb$/

Style/ClassVars:
  Exclude:
    - 'shared_togo/config/initializers/active_record.rb'
    - 'connectors/config/initializers/salesforce_bulk_query.rb'

Style/SignalException:
  Exclude:
    - 'shared_togo/config/initializers/devise.rb'
    - 'frito_pie/config/initializers/devise.rb'
    - 'loco_moco/config/initializers/devise.rb'

# it's ok to use global variables in specs
Style/GlobalVars:
  Exclude:
    - spec/**/*
    - '**/spec/*'

#
# Disabled Rules
#
# If you think one of this rule should be activated,
#
# Make sure there's a team discussion first, so there's a consensus :)
Lint/IneffectiveAccessModifier:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

#
# Allowing Trailing commas (no consensus)
#
Style/TrailingCommaInArguments:
  Enabled: false

#
# Rules to disable any length restriction
#
Metrics/BlockLength:
  Enabled: false

Metrics/BlockNesting:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Layout/LineLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Layout/EmptyLineAfterMagicComment:
  Enabled: false

Layout/EmptyLineBetweenDefs:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/FirstArrayElementIndentation:
  Enabled: false

Layout/FirstHashElementIndentation:
  Enabled: false

Lint/AmbiguousBlockAssociation:
  Enabled: false

Lint/AssignmentInCondition:
  Enabled: false

Lint/ConstantDefinitionInBlock:
  Enabled: false

Lint/MissingSuper:
  Enabled: false

Naming/HeredocDelimiterNaming:
  Enabled: false

Naming/MemoizedInstanceVariableName:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Naming/PredicateName:
  Enabled: false

Performance/RedundantBlockCall:
  Enabled: false

Performance/RegexpMatch:
  Enabled: false

Performance/TimesMap:
  Enabled: false

Style/AccessorGrouping:
  Enabled: false

Style/Alias:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/ClassCheck:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/EmptyElse:
  Enabled: true
  EnforcedStyle: empty

Style/ExpandPathArguments:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/GlobalStdStream:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/HashSyntax:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Style/MultilineIfModifier:
  Enabled: false

Style/MutableConstant:
  Enabled: false

Style/Next:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/OptionalBooleanParameter:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

Style/PreferredHashMethods:
  Enabled: false

Style/RaiseArgs:
  Enabled: false

Style/RedundantFreeze:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/StringConcatenation:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/SymbolProc:
  Enabled: true
  IgnoredMethods:
    - after_transition
    - respond_to

Style/TernaryParentheses:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false

Style/WordArray:
  Enabled: false
