agents:
  provider: "gcp"
  machineType: "n1-standard-8"

defaultTimeoutInMinutes: 5

steps:
  - label: ":wrench: Lint"
    commands:
      - ".buildkite/scripts/run_command.sh docker"
      - ".buildkite/scripts/run_command.sh lint"
