agents:
  provider: "gcp"
  machineType: "n1-standard-8"

steps:
#  - label: ":construction: Build CI docker image"
#    key: "build-ci-docker"
#    commands:
#      - ".buildkite/scripts/run_command.sh docker"

  - label: ":wrench: Lint"
    timeout_in_minutes: 1
    commands:
      - ".buildkite/scripts/run_command.sh docker"
      - ".buildkite/scripts/run_command.sh lint"
