agents:
  provider: "gcp"
  machineType: "n1-standard-8"

steps:
  - label: "Build Docker Image"
    commands:
      - "docker build -t crawler-ci ."
      - ".buildkite/scripts/run_command.sh install"

  - label: ":wrench: Linting"
    timeout_in_minutes: 1
    commands:
      - ".buildkite/scripts/run_command.sh lint"

  - label: "Build"
    command: "true"

  - label: "Test"
    command: "true"

  - label: "Deploy"
    command: "true"

  - label: "Publish"
    command: "true"
