agents:
  provider: "gcp"
  machineType: "n1-standard-8"

defaultTimeoutInMinutes: 5

# TODO: change docker build steps into pulling a ci-agent-image to speed up build time
steps:
  - label: ":rubocop: Lint"
    commands:
      - ".buildkite/scripts/run_command.sh docker"
      - ".buildkite/scripts/run_command.sh lint"
  - label: ":rspec: Test"
    commands:
      - ".buildkite/scripts/run_command.sh docker"
      - ".buildkite/scripts/run_command.sh test"
