---
# $yaml-language-server: $schema=https://raw.githubusercontent.com/buildkite/pipeline-schema/main/schema.json
steps:
  - label: ":wrench: Linting"
    timeout_in_minutes: 1
    command: "make lint"

  - label: "Build"
    command: "true"

  - label: "Test"
    command: "true"

  - label: "Deploy"
    command: "true"

  - label: "Publish"
    command: "true"
