agents:
  provider: "gcp"
  machineType: "n1-standard-8"

steps:
  - label: ":construction: Build CI docker image"
    key: "build-ci-docker"
    commands:
      - "docker build -t crawler-ci /ci/.buildkite"

  - label: ":wrench: Lint"
    timeout_in_minutes: 1
    commands:
      - ".buildkite/scripts/run_command.sh lint"
    depends_on:
      - step: "build-ci-docker"
