#!/bin/bash

source "$(dirname $0)/functions.sh"

set -e

# Used by Gemfile to limit direct access to bundle commands
export SCRIPT_BUNDLE=true

# Tune for faster startup
export JRUBY_OPTS="${JRUBY_OPTS:-} --dev --debug"
export JAVA_OPTS="-Xmx2g ${JAVA_OPTS:-} -Djava.awt.headless=true -Dsun.jnu.encoding=UTF-8 -Dfile.encoding=UTF-8 -XX:+HeapDumpOnOutOfMemoryError"

function bundle_command() {
  if ! bundle "$@"; then
    set +x
    echo
    red_echo "ERROR: Bundle command failed!"
    yellow_echo "Try to run 'make install' and then retry this command"
    echo
    exit 42
  fi
}

BUNDLER_VERSION="$(cat .bundler-version)"
BUNDLER_CONSTRAINT="~> $BUNDLER_VERSION"

blue_echo "Bundling jruby gems..."

blue_echo "Running the bundle command..."
bundle_command "$@"

green_echo "Done!"
echo
