#!/bin/bash

set -e

# Load our common shell functions library
source "$(dirname $0)/functions.sh"

#---------------------------------------------------------------------------------------------------
function bundler_installed() {
  ruby -r bundler -e true 2> /dev/null
}

function install_bundler() {
  yellow_echo "Installing bundler version ${BUNDLER_VERSION}"
  gem install bundler --clear-sources --source=https://rubygems.org -v="${BUNDLER_VERSION}"
}

function reinstall_bundler() {
  yellow_echo "Removing all installed bundler versions and installing bundler version ${BUNDLER_VERSION}..."
  gem uninstall bundler --force --all --ignore-dependencies --executables
  install_bundler
}

function check_bundler_version() {
  ruby -r bundler -e "exit Gem::Requirement.new('${BUNDLER_CONSTRAINT}').satisfied_by?(Gem::Version.new(Bundler::VERSION))"
}

function ensure_bundler_version() {
  RUBY_VERSION="$1"

  yellow_echo "Checking bundler version in $RUBY_VERSION..."
  rbenv shell "$RUBY_VERSION"
  rbenv rehash

  if ! bundler_installed; then
    red_echo "No bundler found in $RUBY_VERSION!"
    install_bundler
  elif ! check_bundler_version; then
    red_echo "ERROR: $RUBY_VERSION bundler version does not satisty the constraint: ${BUNDLER_CONSTRAINT}! Installed version: $(bundler --version)"
    reinstall_bundler
  fi

  bundler --version
  green_echo "Done!"
  echo
}

#---------------------------------------------------------------------------------------------------
BUNDLER_VERSION="$(cat .bundler-version)"
BUNDLER_CONSTRAINT="~> $BUNDLER_VERSION"

JRUBY_VERSION="$(cat .ruby-version)"
JAVA_VERSION="$(cat .java-version)"

echo "----------------------------------------------------------------------------"
echo "Jruby version required: ${JRUBY_VERSION}"
echo "Java version required: ${JAVA_VERSION}"
echo "Bundler version supported: ${BUNDLER_CONSTRAINT} (recommended: ${BUNDLER_VERSION})"
echo "----------------------------------------------------------------------------"
echo

#---------------------------------------------------------------------------------------------------
# Enable jenv and rbenv support
rbenv_init
jenv_init

# Make sure we have the java version we need
ensure_java_installed "$JAVA_VERSION"

#---------------------------------------------------------------------------------------------------
yellow_echo "Making sure jruby $JRUBY_VERSION is installed..."
jenv shell "$JAVA_VERSION"
rbenv install --skip-existing "$JRUBY_VERSION"
green_echo "Done!"
echo

ensure_bundler_version "$JRUBY_VERSION"

#---------------------------------------------------------------------------------------------------
echo "---------------------------------------------------------------------------------------------"
green_echo "Your Ruby environment should be ready for working on the Crawler codebase now"
echo "---------------------------------------------------------------------------------------------"
