name: Force backport labels for main

on:
  pull_request_target:
    branches:
      - main
    types:
      - opened

jobs:
  add_labels:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: version
        uses: juliangruber/read-file-action@386973d5b59f826915775874c7d1f82c4bbcfb07
        with:
          path: ./product_version
      - uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: |
            auto-backport
            v${{ steps.version.outputs.content }}
