name: Backport PR

on:
  pull_request_target:
    branches:
      - main
    types:
      - labeled
      - closed

jobs:
  backport:
    if: |
      github.event.pull_request.merged == true
      && contains(github.event.pull_request.labels.*.name, 'auto-backport')
      && (
        (github.event.action == 'labeled' && github.event.label.name == 'auto-backport')
        || (github.event.action == 'closed')
      )
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Actions
        uses: actions/checkout@v2
        with:
          repository: 'swiftype/kibana-github-actions'
          ref: main
          path: ./actions

      - name: Install Actions
        run: npm install --production --prefix ./actions

      - name: Run Backport
        uses: ./actions/backport
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          approver_token: ${{ secrets.REPO_SCOPED_TOKEN }}
          auto_approve: 'true'
          commit_user: elastic
          commit_email: ent-search-backport@users.noreply.github.com
          auto_merge: 'true'
          auto_merge_method: 'squash'
          manual_backport_command_template: 'backport --pr %pullNumber% --autoMerge --autoMergeMethod squash'
